name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted
    
    env:
      CONTAINER_NAME: myappCommandContainer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          echo "Building Docker image..."
          docker build -t myapp:latest -f ./Dockerfile .

      - name: Stop and Remove Existing Container
        run: |
          CNAME=${{ env.CONTAINER_NAME }}
          if [ "$(docker ps -aq -f name=$CNAME)" ]; then
              if [ "$(docker ps -aq -f status=exited -f name=$CNAME)" ]; then
                  echo ":: Removing exited container - $CNAME"
                  docker rm $CNAME
              else
                  echo ":: Stopping and removing running container - $CNAME"
                  docker stop $CNAME
                  docker rm $CNAME
              fi
          else
              echo ":: No existing container named $CNAME"
          fi

      - name: Run New Docker Container
        run: |
          echo "Starting new container..."
          docker run -d -p 8080:8080 \
            --name ${{ env.CONTAINER_NAME }} \
            myapp:latest